### ISSUE TITLE
Enable versioning on shared venue buckets

### ISSUE THREAD

**Issue by LucaCinquini** [unity-sds/unity-cs#418]
Note: this ticket should be transferred by @galenatjpl to one of the CS GitHub repositories.

When storing the Terraform state of the systems on S3, it is recommended that the S3 bucket be enabled with versioning: this is to be able to recover the state in case of accidental deletion.

See warning in instructions: https://developer.hashicorp.com/terraform/language/settings/backends/s3

"Warning! It is highly recommended that you enable [Bucket Versioning](https://docs.aws.amazon.com/AmazonS3/latest/userguide/manage-versioning-examples.html) on the S3 bucket to allow for state recovery in the case of accidental deletions and human error."

So can we please enable versioning on the bucket "unity-unity-dev-bucket" and all the similar buckets in each venue?

**Comment by galenatjpl** [comment]
@jdrodjpl the s3.go code needs to be updated so that new Management Console deployments enable versioning on the bucket.  Also, for the "blessed" instances/buckets that already exist in unity-venue-dev, unity-venue-test, (and unity-venue-ops?), we may need to go in an manually set this setting in the AWS web console, unless we plan on destroying and re-deploying.  I'm actually in favor of doing the latter (destroy, release a new MC version, and re-deploy).

**Comment by LucaCinquini** [comment]
Please let us know what you decide. We are already using the unity-unity-dev-bucket to store S3 states. If you decide to destroy it, we first need to undeploy SPS, then wait for you to enable versioning. A manual upgrade in the console might be preferable to us, but we can go either way.

**Comment by galenatjpl** [comment]
@jdrodjpl please note @LucaCinquini 's comment above.

**Comment by jdrodjpl** [comment]
@LucaCinquini I went ahead and just enabled the versioning option for both `unity-venue-dev` and `unity-venue-test`, no need to do anything.

**Comment by jdrodjpl** [comment]
@galenatjpl this has been added to the latest MC tag.

**Comment by LucaCinquini** [comment]
Great, thanks guys.

**Comment by galenatjpl** [comment]
thanks @jdrodjpl !
